### ISSUE TITLE
Get-ATWSAccount - Company Category

### ISSUE THREAD

**Issue by MadRainbow** [ecitsolutions/Autotask#116]
I can't seem to find a way of editing (or retrieving) the Company Category field from the get-atwsacount and set-atwsaccount commands.  The field according to the AT API Document is companyCategoryID.

Am I missing something, or is this that may be included in a future build?

Thanks

D

**Comment by klemmestad** [comment]
I'm sorry, but this powershell module is still using the SOAP API, and companyCategoryId is only exposed through the REST API. I have looked into how much work it would be to switch API backend, but the biggest hurdle is that there are quite a few differences between the two. Enough so that I cannot assume backwards compatibility for scripts that have been written using this module. When they end support for the SOAP API this will be a moot point, but it will still be supported for production for another 2 years.
