### ISSUE TITLE
Date fields are incorrect

### ISSUE THREAD

**Issue by jameseleach** [ecitsolutions/Autotask#61]
I'm using version 1.6.2.17 of the module. 

I'm seeing issues with 'date' fields being returned as 23:00:00 the previous day instead of 00:00:00 the day of.   I'm not sure if this was caused by summer time ending, or what, but I don't believe this has been happening for very long.  

Here's an example with `Get-AtwsTimeEntry` that shows the incorrect results. 
```
PS D:\working> Get-AtwsTimeEntry -TicketID 515745 | Select *date*

DateWorked                    : 7/16/2019 11:00:00 PM
StartDateTime                 : 7/17/2019 11:02:00 AM
EndDateTime                   : 7/17/2019 11:16:00 AM
CreateDateTime                : 7/17/2019 11:16:23 AM
LastModifiedDateTime          : 7/17/2019 11:16:23 AM
```

I did some review of other calls that return "date" fields, like contracts (`Get-AtwsContract`), and they are doing the same thing - returning a datetime object that is 11pm the previous day instead of 00:00;00 the day of.   This obviously results in those fields being a day off.    

It's also not possible to query the correct day using these fields without some tricks.   I've got a couple workarounds but am concerned that using them will break again when summer time starts up again.  

I'm in the CST6CDT timezone, which is not currently affected by "Daylight Savings Time" aka: "Summer Time"
```
PS D:\working> Get-TimeZone

Id                         : Central Standard Time
DisplayName                : (UTC-06:00) Central Time (US & Canada)
StandardName               : Central Standard Time
DaylightName               : Central Daylight Time
BaseUtcOffset              : -06:00:00
SupportsDaylightSavingTime : True

```

I've queried the API directly using the PS code examples from the AutotaskDevelopment samples, [here](https://github.com/AutotaskDevelopment/Sample-Code/blob/master/Connection%20Examples/PowerShell%20Example.ps1) and I get the correct date: 

```
PS D:\working> ($atws.query($xml)).EntityResults | Select *date*

DateWorked                    : 7/17/2019 12:00:00 AM
StartDateTime                 : 7/17/2019 12:02:00 PM
EndDateTime                   : 7/17/2019 12:16:00 PM
CreateDateTime                : 7/17/2019 12:16:23 PM
LastModifiedDateTime          : 7/17/2019 12:16:23 PM
```

One last thing... I think this will reliably return `true` or `false` depending on if daylight saving time is active or not:  

```
PS D:\working> ([System.TimeZoneInfo]::ConvertTimeFromUtc((Get-Date).ToUniversalTime(), (Get-TimeZone))).IsDaylightSavingTime()
False
```

Let me know what you think!  

Be well,
James

**Comment by klemmestad** [comment]
Date and datetime is definitely an issue. The API works in EST only. Since I am located in Europe I need to work in local time. This part of the code is improving, however I do have some fixes in the pipeline that will (hopefully) keep dates (should not be localized) separated from datetime (must be localized). All date fields are returned as Datetime, so this is not straight forward.

The issue of dates vs datetime is _mostly_ solved in the current development code, but daylight savings time is a pain. Your problems stems from the code converting all dates and datetime to the _current_ local time. I need to convert the datetime to the correct local time of the datetime itself. 

How do I determine - using .NET classes - whether any given date was "Daylights Savings Time" or "Summer time" in the users current timezone?

I am _so_ looking forward to Europe killing Daylights Savings time - it is certainly not saving any time for coders 😉

**Comment by ArtisanByteCrafter** [comment]
I'm having this issue here as well. I'm in Central Time (CST) and a coworker is in Eastern Time (EST). My coworker performed a request and got 203 results. I performed the same request and got 1 result.

Here is the query:

```powershell
 Get-AtwsTimeEntry -DateWorked '5/6/2020'
```

I modified the following line to remove the offset, as i am wondering if the API is not expecting that. 

https://github.com/ecitsolutions/Autotask/blob/643a1d7e919a1097e8b600d5cb162d92ea59f9b7/Autotask/Private/ConvertTo-AtwsDate.ps1#L59

Specifically i changed line 59 to this string:

```powershell
$value = $DateTime.ToString('yyyy-MM-ddTHH:mm:ss.ffff')
```

After re-importing the module with the 'z' character removed, i also got 203 results.

**Comment by klemmestad** [comment]
Hi @ArtisanByteCrafter 
The Autotask WebAPI returns all datetime fields in EST. This is inconvenient when you live and work in Europe. That is why I have added support for converting dates to and from local time. To do that I convert datetime in queries to sortable datetime, including offset from GMT. So you are right. By removing that 'z' you force the module to treat all datetime in queries as EST. The end result is that you get the exact same result as your colleague who is in EST.

But technically, this is the wrong result if you intended to get all timeentries from a specific date as seen from another timezone. Still, the difference between CST and EST is just one hour. It is a bit weird you get such a different result. I would have liked to see the output of 
```powershell
Get-AtwsTimeEntry -DateWorked '5/6/2020' -Verbose
```
With the original code.

**Comment by ArtisanByteCrafter** [comment]
Sure thing. I have unmodified my v 1.6.6 module and ran a simple test, both from my computer in Central Time, and immediately again from a server in Eastern Time. Both are below. Central time returns only 31 results, while eastern time returns 780 results:

from computer in Central Time:

```powershell
$test = Get-AtwsTimeEntry -DateWorked '5/1/2020' -Debug -Verbose
DEBUG: Get-AtwsTimeEntry: Begin of function
DEBUG: Get-AtwsTimeEntry: Query based on parameters, parsing
DEBUG: ConvertTo-AtwsFilter: Begin of function
DEBUG: Get-AtwsFieldInfo: Begin of function
VERBOSE: Get-AtwsFieldInfo: Looking up detailed Fieldinfo for entity TimeEntry
DEBUG: Get-AtwsFieldInfo: Returning fieldinfo for entity TimeEntry from cache
DEBUG: Get-AtwsFieldInfo: End of function
DEBUG: ConvertTo-AtwsFilter: Query based on parameters, parsing
DEBUG: ConvertTo-AtwsDate: Input Value: 5/1/2020 12:00:00 AM
VERBOSE: ConvertTo-AtwsDate: Converting datetime to 2020-05-01T00:00:00.0000-5
DEBUG: ConvertTo-AtwsDate: Output value: 2020-05-01T00:00:00.0000-5
DEBUG: ConvertTo-AtwsDate: Input Value: 5/2/2020 12:00:00 AM
VERBOSE: ConvertTo-AtwsDate: Converting datetime to 2020-05-02T00:00:00.0000-5
DEBUG: ConvertTo-AtwsDate: Output value: 2020-05-02T00:00:00.0000-5
VERBOSE: Get-AtwsTimeEntry: About to query the Autotask Web API for TimeEntry(s).
DEBUG: Get-AtwsData: Begin of function
VERBOSE: Get-AtwsData: Converting query string into QueryXml. string as array looks like: TimeEntry, DateWorked, -ge, 2020-05-01T00:00:00.0000-5, DateWorked, -le, 2020-05-02T00:00:00.0000-5
DEBUG: Get-AtwsData: QueryXml looks like: <queryxml><entity>TimeEntry</entity><query><field>DateWorked<expression op="GreaterThanorEquals">2020-05-01T00:00:00.0000-5</expression></field><field>DateWorked<expression op="LessThanOrEquals">2020-05-02T00:00:00.0000-5</expression></field></query></queryxml>
VERBOSE: Get-AtwsData: Adding looping construct to query to handle more than 500 results.
VERBOSE: Get-AtwsData: Passing QueryXML to Autotask API
DEBUG: ConvertTo-LocalObject: Begin of function
DEBUG: Get-AtwsFieldInfo: Begin of function
VERBOSE: Get-AtwsFieldInfo: Looking up detailed Fieldinfo for entity TimeEntry
DEBUG: Get-AtwsFieldInfo: Returning fieldinfo for entity TimeEntry from cache
DEBUG: Get-AtwsFieldInfo: End of function
DEBUG: ConvertTo-LocalObject: End of function, returning 31 TimeEntry(s)
DEBUG: Get-AtwsData: End of function
VERBOSE: Get-AtwsTimeEntry: Number of entities returned by base query: 31
DEBUG: Get-AtwsTimeEntry: End of function
```

A count of results from CST: 
```powershell
PS> $test.count
31
```

And the same from a computer in Eastern Time, executed a few seconds later.

```powershell
PS> $test = Get-AtwsTimeEntry -DateWorked '5/1/2020' -Debug -Verbose
DEBUG: Get-AtwsTimeEntry: Begin of function
DEBUG: Get-AtwsTimeEntry: Query based on parameters, parsing
DEBUG: ConvertTo-AtwsFilter: Begin of function
DEBUG: Get-AtwsFieldInfo: Begin of function
VERBOSE: Get-AtwsFieldInfo: Looking up detailed Fieldinfo for entity TimeEntry
DEBUG: Get-AtwsFieldInfo: Returning fieldinfo for entity TimeEntry from cache
DEBUG: Get-AtwsFieldInfo: End of function
DEBUG: ConvertTo-AtwsFilter: Query based on parameters, parsing
DEBUG: ConvertTo-AtwsDate: Input Value: 5/1/2020 12:00:00 AM
VERBOSE: ConvertTo-AtwsDate: Converting datetime to 2020-05-01T00:00:00.0000-4
DEBUG: ConvertTo-AtwsDate: Output value: 2020-05-01T00:00:00.0000-4
DEBUG: ConvertTo-AtwsDate: Input Value: 5/2/2020 12:00:00 AM
VERBOSE: ConvertTo-AtwsDate: Converting datetime to 2020-05-02T00:00:00.0000-4
DEBUG: ConvertTo-AtwsDate: Output value: 2020-05-02T00:00:00.0000-4
VERBOSE: Get-AtwsTimeEntry: About to query the Autotask Web API for TimeEntry(s).
DEBUG: Get-AtwsData: Begin of function
VERBOSE: Get-AtwsData: Converting query string into QueryXml. string as array looks like: TimeEntry, DateWorked, -ge, 2020-05-01T00:00:00.0000-4, DateWorked, -le, 2020-05-02T00:00:00.0000-4
DEBUG: Get-AtwsData: QueryXml looks like: <queryxml><entity>TimeEntry</entity><query><field>DateWorked<expression
op="GreaterThanorEquals">2020-05-01T00:00:00.0000-4</expression></field><field>DateWorked<expression op="LessThanOrEquals">2020-05-02T00:00:00.0000-4</expression></field></query></queryxml>
VERBOSE: Get-AtwsData: Adding looping construct to query to handle more than 500 results.
VERBOSE: Get-AtwsData: Passing QueryXML to Autotask API
DEBUG: ConvertTo-LocalObject: Begin of function
DEBUG: Get-AtwsFieldInfo: Begin of function
VERBOSE: Get-AtwsFieldInfo: Looking up detailed Fieldinfo for entity TimeEntry
DEBUG: Get-AtwsFieldInfo: Returning fieldinfo for entity TimeEntry from cache
DEBUG: Get-AtwsFieldInfo: End of function
DEBUG: ConvertTo-LocalObject: End of function, returning 500 TimeEntry(s)
VERBOSE: Get-AtwsData: Passing QueryXML to Autotask API
DEBUG: ConvertTo-LocalObject: Begin of function
DEBUG: Get-AtwsFieldInfo: Begin of function
VERBOSE: Get-AtwsFieldInfo: Looking up detailed Fieldinfo for entity TimeEntry
DEBUG: Get-AtwsFieldInfo: Returning fieldinfo for entity TimeEntry from cache
DEBUG: Get-AtwsFieldInfo: End of function
DEBUG: ConvertTo-LocalObject: End of function, returning 280 TimeEntry(s)
DEBUG: Get-AtwsData: End of function
VERBOSE: Get-AtwsTimeEntry: Number of entities returned by base query: 780
DEBUG: Get-AtwsTimeEntry: End of function
```

A count of results from EST: 
```powershell
PS> $test.count
780
```

**Comment by ArtisanByteCrafter** [comment]
I'd also like to add this, after some additional detective work. I ran the following exact same code across two different versions of the module - 0.2.2.5 (returns as expected) and 1.6.6 (returns way more than expected).

I tried to run a single query:

**Autotask Version 0.2.2.5**
```powershell
$StartDate = ([datetime]'5/1/2020')
$EndDate = [datetime]::today

$dateArray = while ($StartDate -le $EndDate){
    get-date $StartDate -f "M/d/yyyy"
    $StartDate = ($StartDate).AddDays(1)
}

$billingItems = Get-AtwsBillingItem -PostedDate $dateArray

$Billingitems.count
1300
```


**Autotask Version 1.6.6**
```powershell
$StartDate = ([datetime]'5/1/2020')
$EndDate = [datetime]::today

$dateArray = while ($StartDate -le $EndDate){
    get-date $StartDate -f "M/d/yyyy"
    $StartDate = ($StartDate).AddDays(1)
}

$billingItems = Get-AtwsBillingItem -PostedDate $dateArray

$Billingitems.count
548643
```

I had a suspicion that the 1.6.6 version was returning every billing item in our org's history, and I believe that's the case. When you look at the verbose output, the operators seem to confirm that theory. On the left is 0.2.2.5 and it uses the `-eq` operator. At some point, this was changed to using `-le` which seems to be going back and retrieving every single item in its history instead of honoring the date filters given.

![image](https://user-images.githubusercontent.com/2523522/81609956-58abee80-939e-11ea-8ad1-44d48dd5728c.png)

**Comment by klemmestad** [comment]
Thank you, that is definitely a bug.

Handling datetime is a constant source of pain, as neither the API nor PowerShell separates date fields from datetime fields. Like your timeentry query. You would expect this query:
```powershell
Get-AtwsTimeEntry -DateWorked '5/6/2020' 
```
to return all timeentries from May 6th, right? Wrong. If I posted that query to the API literally, i.e. 
```powershell
Get-AtwsTimeEntry -Filter {DateWorked -eq '5/6/2020'}
```
you would most likely get zero results. Because the API would be looking for time entries with a WorkedDate_Time_ of '5/6/2020 00:00:00'. So I added code to expand dates into a filter that includes all datetime from midnight until midnight. This, of course is a timezone dependent filter.

And your example clearly show that there is a bug in that code. I will look into it!

**Comment by klemmestad** [comment]
BTW: Workarounds:
```powershell
# The simplest, provided EndDate always is today
$StartDate = ([datetime]'5/1/2020')
$billingItems = Get-AtwsBillingItem -PostedDate $StartDate -GreaterThan PostedDate
$billingItems.count

# The precise (covers specific timespan)
$EndDate = [datetime]::today
$billingItems = Get-AtwsBillingItem -Filter {PostedDate -ge $StartDate -and PostedDate -le $EndDate}
$billingItems.count
```
Hope that helps while you wait for a fix.

**Comment by ArtisanByteCrafter** [comment]
This workaround seems to work perfectly, thank you so much! If you need any help working out any bugs for different timezones, I'm in CST, and have resources in EST, so please feel free to reach out if needed.

**Comment by klemmestad** [comment]
Thank you again, @ArtisanByteCrafter, I will do that! When I have fixed my code I will let you know 😉

**Comment by klemmestad** [comment]
Module 1.6.7 is out with a fix for the multiple date values bug. The workaround is still the best way of querying for a date interval, though. And the timezone challenges are still mostly unsolved.
