### ISSUE TITLE
Import-Module path issues - Powershell for Mac

### ISSUE THREAD

**Issue by DeepCode9513** [ecitsolutions/Autotask#67]
There seems to be some path issues when the modules are run on Powershell for mac - path separators are hard coded as ';' and mac uses ':'

**Comment by klemmestad** [comment]
I'm sorry, but despite being a pure script-module it doesn't work on a mac. It still depends on new-webserviceproxy [which uses .NET libraries that isn't included in .NET core](https://github.com/PowerShell/PowerShell/issues/9838). Since I am a mac user myself and we only need it to work with a single SOAP API, not every SOAP API there is, I have some ideas, but I do not have any working code as of yet.

**Comment by klemmestad** [comment]
I have published a module version AutotaksBeta on PowershellGallery with multiplatform support. It should load and run on a mac. Install with `install-module autotaskbeta` and you can use it just like the release module: `import-module autotaskbeta; connect-atwswebapi ...`

it works just like the main module in my tests, but since the core method for communication with autotask has been changed it needs a lot of testing before I can release it as the main module version. It would be very useful if you could try it out 😊

**Comment by klemmestad** [comment]
PowerShell Core 6 and 7 support is now available in the in-line beta version: `Update-Module Autotask -AllowPreRelease`. It works like a charm on both macOS and Linux in our testing.
