### ISSUE TITLE
Set-ATWSTicket issue

### ISSUE THREAD

**Issue by Superfluxus** [ecitsolutions/Autotask#76]
When trying to set the description/title of a ticket using the Set-ATWSTicket cmdlet, I am getting the following error:
```

`Exception setting "Id": "Cannot convert the "System.Int64[]" value of type "System.Int64[]" to type "System.Int64"."
At C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.11\Dynamic\Set-AtwsTicket.ps1:703 char:21
+           $Object.$($Parameter.Key) = $Value
+                     ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting`

```
This is the code I am using:
```

`$Ticket = Get-ATWSTicket -id 999
$ID = $Ticket.ID
    Set-ATWSTicket -ID $ID -Description "Test" -Title "Test" -Status "Complete"
`
```

For what it's worth, here is the type of my variable:
```

`$id.gettype()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Int64                                    `System.ValueType``

```
Struggle to reproduce consistently, seems to work about 40% of the time.

**Comment by klemmestad** [comment]
This should have worked, but from your error message is looks like you are still using module version 1.6.2.11. Most recent version is 1.6.5. This issue is hopefully solved in the current version.

There may be a reason for why you choose to extract the ticket id in a separate step, but because I know how the module works and which operations are expensive in terms of making calls to the API, I would suggest you try something like this instead:
```powershell
$Ticket = Get-ATWSTicket -id 999
Set-ATWSTicket -InputObject $Ticket -Description "Test" -Title "Test" -Status "Complete"
```
Which is the equivalent of doing:
```powershell
$Ticket = Get-ATWSTicket -id 999
$Ticket | Set-ATWSTicket -Description "Test" -Title "Test" -Status "Complete"
```
However, for more than 1 ticket you should use `-InputObject` as it is much faster (a single call to the API for every 200 objects in place of a call pr object).

**Comment by Superfluxus** [comment]
Ah thankyou for the advice! I will update the module and endeavor to make better use of the -inputobject argument.

Thanks again :)
