### ISSUE TITLE
TimeZone issues

### ISSUE THREAD

**Issue by bjowol** [ecitsolutions/Autotask#94]
Most notable when working with adjusting CSUs.

It looks like there are timezoen issues again. Something has probably changed from the Autotask API side. probably from the 1.6 version, og the recent november updates.
Im in the +1 timezome in europe/norway, not that many of you may use the CSUs adjustment options, and most of you are probably in the USA. The autotask APi default TimeZone is -6 i believe. 

Noticed when the module returned 0 CSUs active on our age old not chaged query to get "todays active CSUs"
`Get-AtwsContractServiceUnit -ContractID $UsedContractIDs -ServiceID $AtwsServices.id -StartDate $Now -LessThanOrEquals StartDate -EndDate $Now -GreaterThanOrEquals EndDate`
This no longer works as expedted. 
Also, noticed when adjusting CSUs the affected date is one way less than today, ergo yesterday, when changing a unit. 

We have to do some research as to how the Autotask SOAP api handles timezones, and build new query structures for this. Maybe the solutions is to port the module over to the REST api to remedy the issue.

Excuse my bad grammar, im writing this in a hurry atm.

**Comment by bjowol** [comment]
iv actually only tested the 2.0.x versions.

**Comment by SjoerdSlabbers** [comment]
Looks like some more issues with time converts;
Exception calling "ConvertTime" with "3" argument(s): "The conversion could not be completed because the supplied DateTime did not have the Kind property set correctly.  For example, when the Kind property is DateTimeKind.Local, the source time zone must be TimeZoneInfo.Local.
Parameter name: sourceTimeZone"
At C:\Program Files\WindowsPowerShell\Modules\AutoTask\1.6.11\Private\ConvertTo-LocalObject.ps1:96 char:21
+ ...             $object.$dateTimeParam = [TimeZoneInfo]::ConvertTime($val ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

**Comment by klemmestad** [comment]
This issue has a fix in the Development branch.
